---
- name: Install AWS CLI, Azure CLI, Terraform, and kubectl on localhost using Homebrew
  hosts: localhost
  become: no  # Homebrew should not be installed as root
  gather_facts: yes

  vars_prompt:
    - name: git_name
      prompt: "Git user.name (full name)"
      private: no
    - name: git_email
      prompt: "Git user.email"
      private: no

  vars:
    kubectl_version: "1.33"

  roles:
    - dev_workstation
